[I 2025-02-24 17:17:16,094] A new study created in RDB with name: NODE_Diamonds
[W 2025-02-24 17:26:10,810] Trial 0 failed with parameters: {'num_layers': 2, 'total_tree_count': 1024, 'tree_depth': 8, 'tree_output_dim': 2} because of the following error: FileNotFoundError('output/NODE/Diamonds/logging//loss_0.txt not found.').
Traceback (most recent call last):
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "train.py", line 137, in __call__
    sc, time = cross_validation(model, self.X, self.y, self.args, visual=True, save_model=False)
  File "train.py", line 89, in cross_validation
    losses = losses_history(args)
  File "train.py", line 108, in losses_history
    loss_file = np.loadtxt(loss_path)
  File "/home/mburu/anaconda3/envs/Tab4Node/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1356, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/mburu/anaconda3/envs/Tab4Node/lib/python3.8/site-packages/numpy/lib/npyio.py", line 975, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/mburu/anaconda3/envs/Tab4Node/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/mburu/anaconda3/envs/Tab4Node/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: output/NODE/Diamonds/logging//loss_0.txt not found.
[W 2025-02-24 17:26:11,615] Trial 0 failed with value None.
Traceback (most recent call last):
  File "train.py", line 188, in <module>
    main(arguments)
  File "train.py", line 159, in main
    study.optimize(Objective(args, model_name, X, y), n_trials=args.n_trials)
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/home/mburu/.local/lib/python3.8/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "train.py", line 137, in __call__
    sc, time = cross_validation(model, self.X, self.y, self.args, visual=True, save_model=False)
  File "train.py", line 89, in cross_validation
    losses = losses_history(args)
  File "train.py", line 108, in losses_history
    loss_file = np.loadtxt(loss_path)
  File "/home/mburu/anaconda3/envs/Tab4Node/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1356, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/mburu/anaconda3/envs/Tab4Node/lib/python3.8/site-packages/numpy/lib/npyio.py", line 975, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/mburu/anaconda3/envs/Tab4Node/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/mburu/anaconda3/envs/Tab4Node/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: output/NODE/Diamonds/logging//loss_0.txt not found.
srun: error: stud-000: task 0: Exited with exit code 1
