Traceback (most recent call last):
  File "/home/mburu/miniconda3/envs/MasterThesis/lib/python3.10/site-packages/httplib2/__init__.py", line 1366, in _conn_request
    conn.connect()
  File "/home/mburu/miniconda3/envs/MasterThesis/lib/python3.10/site-packages/httplib2/__init__.py", line 1142, in connect
    address_info = socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM)
  File "/home/mburu/miniconda3/envs/MasterThesis/lib/python3.10/socket.py", line 967, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mburu/Master_Thesis/master-thesis-da/wrangling/wrangle_drive.py", line 37, in <module>
    download_folder(root_folder_id, local_path)
  File "/home/mburu/Master_Thesis/master-thesis-da/wrangling/wrangle_drive.py", line 19, in download_folder
    file_list = drive.ListFile({'q': f"'{folder_id}' in parents and trashed=false"}).GetList()
  File "/home/mburu/miniconda3/envs/MasterThesis/lib/python3.10/site-packages/pydrive/apiattr.py", line 162, in GetList
    for x in self:
  File "/home/mburu/miniconda3/envs/MasterThesis/lib/python3.10/site-packages/pydrive/apiattr.py", line 146, in __next__
    result = self._GetList()
  File "/home/mburu/miniconda3/envs/MasterThesis/lib/python3.10/site-packages/pydrive/auth.py", line 75, in _decorated
    return decoratee(self, *args, **kwargs)
  File "/home/mburu/miniconda3/envs/MasterThesis/lib/python3.10/site-packages/pydrive/files.py", line 63, in _GetList
    self.metadata = self.auth.service.files().list(**dict(self)).execute(
  File "/home/mburu/miniconda3/envs/MasterThesis/lib/python3.10/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/mburu/miniconda3/envs/MasterThesis/lib/python3.10/site-packages/googleapiclient/http.py", line 923, in execute
    resp, content = _retry_request(
  File "/home/mburu/miniconda3/envs/MasterThesis/lib/python3.10/site-packages/googleapiclient/http.py", line 222, in _retry_request
    raise exception
  File "/home/mburu/miniconda3/envs/MasterThesis/lib/python3.10/site-packages/googleapiclient/http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/home/mburu/miniconda3/envs/MasterThesis/lib/python3.10/site-packages/oauth2client/transport.py", line 159, in new_request
    credentials._refresh(orig_request_method)
  File "/home/mburu/miniconda3/envs/MasterThesis/lib/python3.10/site-packages/oauth2client/client.py", line 749, in _refresh
    self._do_refresh_request(http)
  File "/home/mburu/miniconda3/envs/MasterThesis/lib/python3.10/site-packages/oauth2client/client.py", line 778, in _do_refresh_request
    resp, content = transport.request(
  File "/home/mburu/miniconda3/envs/MasterThesis/lib/python3.10/site-packages/oauth2client/transport.py", line 280, in request
    return http_callable(uri, method=method, body=body, headers=headers,
  File "/home/mburu/miniconda3/envs/MasterThesis/lib/python3.10/site-packages/httplib2/__init__.py", line 1724, in request
    (response, content) = self._request(
  File "/home/mburu/miniconda3/envs/MasterThesis/lib/python3.10/site-packages/httplib2/__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/mburu/miniconda3/envs/MasterThesis/lib/python3.10/site-packages/httplib2/__init__.py", line 1373, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
httplib2.error.ServerNotFoundError: Unable to find the server at oauth2.googleapis.com
srun: error: stud-000: task 0: Exited with exit code 1
